// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build cgo

package arith

import (
	"fmt"

	mlir "github.com/timmyyuan/mlir-go"
)

func ConstantOp(ctx *mlir.Context, loc mlir.Location, resultType mlir.Type, value mlir.Attribute) (*mlir.OwnedOperation, error) {
	if resultType.IsNull() {
		return nil, fmt.Errorf("mlir: result type is required")
	}
	if value.IsNull() {
		return nil, fmt.Errorf("mlir: value attribute is required")
	}
	valueAttr, err := mlir.NamedAttributeByName(ctx, "value", value)
	if err != nil {
		return nil, err
	}
	state := mlir.NewOperationState("arith.constant", loc)
	state.AddResults(resultType)
	state.AddAttributes(valueAttr)
	return mlir.CreateOperation(state)
}

func AddIOp(loc mlir.Location, lhs, rhs mlir.Value) (*mlir.OwnedOperation, error) {
	return emitSameTypeBinaryOp("arith.addi", loc, lhs, rhs)
}

func SubIOp(loc mlir.Location, lhs, rhs mlir.Value) (*mlir.OwnedOperation, error) {
	return emitSameTypeBinaryOp("arith.subi", loc, lhs, rhs)
}

func MulIOp(loc mlir.Location, lhs, rhs mlir.Value) (*mlir.OwnedOperation, error) {
	return emitSameTypeBinaryOp("arith.muli", loc, lhs, rhs)
}

func ExtUIOp(loc mlir.Location, input mlir.Value, resultType mlir.Type) (*mlir.OwnedOperation, error) {
	return emitUnaryCastOp("arith.extui", loc, input, resultType)
}

func ExtSIOp(loc mlir.Location, input mlir.Value, resultType mlir.Type) (*mlir.OwnedOperation, error) {
	return emitUnaryCastOp("arith.extsi", loc, input, resultType)
}

func TruncIOp(loc mlir.Location, input mlir.Value, resultType mlir.Type) (*mlir.OwnedOperation, error) {
	return emitUnaryCastOp("arith.trunci", loc, input, resultType)
}

func SIToFPOp(loc mlir.Location, input mlir.Value, resultType mlir.Type) (*mlir.OwnedOperation, error) {
	return emitUnaryCastOp("arith.sitofp", loc, input, resultType)
}

func FPToSIOp(loc mlir.Location, input mlir.Value, resultType mlir.Type) (*mlir.OwnedOperation, error) {
	return emitUnaryCastOp("arith.fptosi", loc, input, resultType)
}

func IndexCastOp(loc mlir.Location, input mlir.Value, resultType mlir.Type) (*mlir.OwnedOperation, error) {
	return emitUnaryCastOp("arith.index_cast", loc, input, resultType)
}

func CmpIOp(ctx *mlir.Context, loc mlir.Location, predicate string, lhs, rhs mlir.Value) (*mlir.OwnedOperation, error) {
	if lhs.IsNull() || rhs.IsNull() {
		return nil, fmt.Errorf("mlir: operands are required")
	}
	resultType, err := cmpIResultType(ctx, lhs.Type(), rhs.Type())
	if err != nil {
		return nil, err
	}
	predicateAttr, err := cmpIPredicateAttr(ctx, predicate)
	if err != nil {
		return nil, err
	}
	predicateNamedAttr, err := mlir.NamedAttributeByName(ctx, "predicate", predicateAttr)
	if err != nil {
		return nil, err
	}
	state := mlir.NewOperationState("arith.cmpi", loc)
	state.AddResults(resultType)
	state.AddOperands(lhs, rhs)
	state.AddAttributes(predicateNamedAttr)
	return mlir.CreateOperation(state)
}

func emitSameTypeBinaryOp(name string, loc mlir.Location, lhs, rhs mlir.Value) (*mlir.OwnedOperation, error) {
	if lhs.IsNull() || rhs.IsNull() {
		return nil, fmt.Errorf("mlir: operands are required")
	}
	resultType := lhs.Type()
	if resultType.IsNull() || !resultType.Equal(rhs.Type()) {
		return nil, fmt.Errorf("mlir: operands must have the same non-null type")
	}
	state := mlir.NewOperationState(name, loc)
	state.AddResults(resultType)
	state.AddOperands(lhs, rhs)
	return mlir.CreateOperation(state)
}

func emitUnaryCastOp(name string, loc mlir.Location, input mlir.Value, resultType mlir.Type) (*mlir.OwnedOperation, error) {
	if input.IsNull() {
		return nil, fmt.Errorf("mlir: input operand is required")
	}
	if resultType.IsNull() {
		return nil, fmt.Errorf("mlir: result type is required")
	}
	state := mlir.NewOperationState(name, loc)
	state.AddResults(resultType)
	state.AddOperands(input)
	return mlir.CreateOperation(state)
}

func cmpIPredicateAttr(ctx *mlir.Context, predicate string) (mlir.Attribute, error) {
	i64, err := mlir.SignlessIntegerType(ctx, 64)
	if err != nil {
		return mlir.Attribute{}, err
	}
	code, ok := map[string]int64{"eq": 0, "ne": 1, "slt": 2, "sle": 3, "sgt": 4, "sge": 5, "ult": 6, "ule": 7, "ugt": 8, "uge": 9}[predicate]
	if !ok {
		return mlir.Attribute{}, fmt.Errorf("mlir: unsupported cmpi predicate %q", predicate)
	}
	return mlir.IntegerAttribute(i64, code)
}

func cmpIResultType(ctx *mlir.Context, lhsType, rhsType mlir.Type) (mlir.Type, error) {
	if lhsType.IsNull() || rhsType.IsNull() || !lhsType.Equal(rhsType) {
		return mlir.Type{}, fmt.Errorf("mlir: cmpi operands must have the same non-null type")
	}
	if lhsType.IsInteger() || lhsType.IsIndex() {
		return mlir.SignlessIntegerType(ctx, 1)
	}
	if lhsType.IsRankedTensor() {
		i1, err := mlir.SignlessIntegerType(ctx, 1)
		if err != nil {
			return mlir.Type{}, err
		}
		return mlir.RankedTensorType(lhsType.Shape(), i1)
	}
	return mlir.Type{}, fmt.Errorf("mlir: cmpi currently supports scalar integers, index values, and ranked tensors")
}
