// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build !cgo

package arith

import (
	"fmt"

	mlir "github.com/timmyyuan/mlir-go"
)

func ConstantOp(*mlir.Context, mlir.Location, mlir.Type, mlir.Attribute) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func AddIOp(mlir.Location, mlir.Value, mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func SubIOp(mlir.Location, mlir.Value, mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func MulIOp(mlir.Location, mlir.Value, mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func ExtUIOp(mlir.Location, mlir.Value, mlir.Type) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func ExtSIOp(mlir.Location, mlir.Value, mlir.Type) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func TruncIOp(mlir.Location, mlir.Value, mlir.Type) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func SIToFPOp(mlir.Location, mlir.Value, mlir.Type) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func FPToSIOp(mlir.Location, mlir.Value, mlir.Type) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func IndexCastOp(mlir.Location, mlir.Value, mlir.Type) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func CmpIOp(*mlir.Context, mlir.Location, string, mlir.Value, mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}
