// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build !cgo

package tensor

import (
	"fmt"

	mlir "github.com/timmyyuan/mlir-go"
)

func EmptyOp(mlir.Location, mlir.Type, ...mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func DimOp(mlir.Location, mlir.Value, mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func CastOp(mlir.Location, mlir.Value, mlir.Type) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}
