// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build cgo

package tensor

import (
	"fmt"

	mlir "github.com/timmyyuan/mlir-go"
)

func EmptyOp(loc mlir.Location, resultType mlir.Type, dynamicSizes ...mlir.Value) (*mlir.OwnedOperation, error) {
	if resultType.IsNull() {
		return nil, fmt.Errorf("mlir: result type is required")
	}
	if !resultType.IsRankedTensor() {
		return nil, fmt.Errorf("mlir: tensor.empty expects a ranked tensor result type")
	}
	expectedDynamic := 0
	for _, dim := range resultType.Shape() {
		if mlir.IsDynamicSize(dim) {
			expectedDynamic++
		}
	}
	if len(dynamicSizes) != expectedDynamic {
		return nil, fmt.Errorf("mlir: tensor.empty expects %d dynamic sizes, got %d", expectedDynamic, len(dynamicSizes))
	}
	state := mlir.NewOperationState("tensor.empty", loc)
	state.AddResults(resultType)
	state.AddOperands(dynamicSizes...)
	return mlir.CreateOperation(state)
}

func DimOp(loc mlir.Location, source mlir.Value, index mlir.Value) (*mlir.OwnedOperation, error) {
	if source.IsNull() || index.IsNull() {
		return nil, fmt.Errorf("mlir: source and index operands are required")
	}
	if !index.Type().IsIndex() {
		return nil, fmt.Errorf("mlir: tensor.dim index operand must have index type")
	}
	state := mlir.NewOperationState("tensor.dim", loc)
	state.AddResults(index.Type())
	state.AddOperands(source, index)
	return mlir.CreateOperation(state)
}

func CastOp(loc mlir.Location, source mlir.Value, resultType mlir.Type) (*mlir.OwnedOperation, error) {
	if source.IsNull() {
		return nil, fmt.Errorf("mlir: source operand is required")
	}
	if resultType.IsNull() {
		return nil, fmt.Errorf("mlir: result type is required")
	}
	state := mlir.NewOperationState("tensor.cast", loc)
	state.AddResults(resultType)
	state.AddOperands(source)
	return mlir.CreateOperation(state)
}
