// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build !cgo

package funcdialect

import (
	"fmt"

	mlir "github.com/timmyyuan/mlir-go"
)

func FuncOp(*mlir.Context, mlir.Location, string, mlir.Type, *mlir.OwnedRegion) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func CallOp(*mlir.Context, mlir.Location, string, []mlir.Type, ...mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func ReturnOp(mlir.Location, ...mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}
