// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build !cgo

package cf

import (
	"fmt"

	mlir "github.com/timmyyuan/mlir-go"
)

func BranchOp(mlir.Location, mlir.Block, ...mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func CondBranchOp(*mlir.Context, mlir.Location, mlir.Value, mlir.Block, []mlir.Value, mlir.Block, []mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}
