// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build !cgo

package memref

import (
	"fmt"

	mlir "github.com/timmyyuan/mlir-go"
)

func AllocaOp(*mlir.Context, mlir.Location, mlir.Type, ...mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func LoadOp(mlir.Location, mlir.Value, ...mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func StoreOp(mlir.Location, mlir.Value, mlir.Value, ...mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}
