// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build cgo

package vector

import (
	"fmt"
	"math"

	mlir "github.com/timmyyuan/mlir-go"
)

func BroadcastOp(loc mlir.Location, source mlir.Value, resultType mlir.Type) (*mlir.OwnedOperation, error) {
	if source.IsNull() {
		return nil, fmt.Errorf("mlir: source operand is required")
	}
	if resultType.IsNull() {
		return nil, fmt.Errorf("mlir: result type is required")
	}
	state := mlir.NewOperationState("vector.broadcast", loc)
	state.AddResults(resultType)
	state.AddOperands(source)
	return mlir.CreateOperation(state)
}

func ExtractOp(ctx *mlir.Context, loc mlir.Location, vector mlir.Value, resultType mlir.Type, staticPosition []int64, dynamicPosition ...mlir.Value) (*mlir.OwnedOperation, error) {
	if vector.IsNull() {
		return nil, fmt.Errorf("mlir: vector operand is required")
	}
	if resultType.IsNull() {
		return nil, fmt.Errorf("mlir: result type is required")
	}
	if len(staticPosition) == 0 && len(dynamicPosition) > 0 {
		staticPosition = make([]int64, len(dynamicPosition))
		for i := range staticPosition {
			staticPosition[i] = math.MinInt64
		}
	}
	attr, err := mlir.DenseI64ArrayAttribute(ctx, staticPosition)
	if err != nil {
		return nil, err
	}
	staticPositionAttr, err := mlir.NamedAttributeByName(ctx, "static_position", attr)
	if err != nil {
		return nil, err
	}
	state := mlir.NewOperationState("vector.extract", loc)
	state.AddResults(resultType)
	state.AddOperands(vector)
	state.AddOperands(dynamicPosition...)
	state.AddAttributes(staticPositionAttr)
	return mlir.CreateOperation(state)
}
