// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build cgo

package vector

import (
	"fmt"

	mlir "github.com/timmyyuan/mlir-go"
)

func BroadcastOp(loc mlir.Location, source mlir.Value, resultType mlir.Type) (*mlir.OwnedOperation, error) {
	if source.IsNull() {
		return nil, fmt.Errorf("mlir: source operand is required")
	}
	if resultType.IsNull() {
		return nil, fmt.Errorf("mlir: result type is required")
	}
	state := mlir.NewOperationState("vector.broadcast", loc)
	state.AddResults(resultType)
	state.AddOperands(source)
	return mlir.CreateOperation(state)
}

func ExtractElementOp(loc mlir.Location, vector mlir.Value, resultType mlir.Type, position ...mlir.Value) (*mlir.OwnedOperation, error) {
	if vector.IsNull() {
		return nil, fmt.Errorf("mlir: vector operand is required")
	}
	if resultType.IsNull() {
		return nil, fmt.Errorf("mlir: result type is required")
	}
	if len(position) > 1 {
		return nil, fmt.Errorf("mlir: vector.extractelement accepts at most one dynamic position")
	}
	state := mlir.NewOperationState("vector.extractelement", loc)
	state.AddResults(resultType)
	state.AddOperands(vector)
	state.AddOperands(position...)
	return mlir.CreateOperation(state)
}
