// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build !cgo

package vector

import (
	"fmt"

	mlir "github.com/timmyyuan/mlir-go"
)

func BroadcastOp(mlir.Location, mlir.Value, mlir.Type) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func ExtractElementOp(mlir.Location, mlir.Value, mlir.Type, ...mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}
