// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build cgo

package linalg

import mlir "github.com/timmyyuan/mlir-go"

func IndexOp(ctx *mlir.Context, loc mlir.Location, dim int64) (*mlir.OwnedOperation, error) {
	indexType, err := mlir.IndexType(ctx)
	if err != nil {
		return nil, err
	}
	i64, err := mlir.SignlessIntegerType(ctx, 64)
	if err != nil {
		return nil, err
	}
	dimAttr, err := mlir.IntegerAttribute(i64, dim)
	if err != nil {
		return nil, err
	}
	dimNamedAttr, err := mlir.NamedAttributeByName(ctx, "dim", dimAttr)
	if err != nil {
		return nil, err
	}
	state := mlir.NewOperationState("linalg.index", loc)
	state.AddResults(indexType)
	state.AddAttributes(dimNamedAttr)
	return mlir.CreateOperation(state)
}

func YieldOp(loc mlir.Location, values ...mlir.Value) (*mlir.OwnedOperation, error) {
	state := mlir.NewOperationState("linalg.yield", loc)
	state.AddOperands(values...)
	return mlir.CreateOperation(state)
}
