// Code generated by cmd/mlir-go-tblgen; DO NOT EDIT.
//go:build !cgo

package linalg

import (
	"fmt"

	mlir "github.com/timmyyuan/mlir-go"
)

func IndexOp(*mlir.Context, mlir.Location, int64) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}

func YieldOp(mlir.Location, ...mlir.Value) (*mlir.OwnedOperation, error) {
	return nil, fmt.Errorf("mlir: cgo is required")
}
